### ISSUE TITLE
Issue with Montreal

### ISSUE THREAD

**Issue by tabooki** [ephro/nhl-notifier#1]
Just installing and testing your code here. Exactly what I am looking for.
Thanks
Waiting for a game to start though to see if it works. ;)

In the meanwhile I get errors scrolling by regarding Montreal. Thought you might like to know.

  File "notifier.py", line 45, in __init__
    self.home = Team(home, home_score)
  File "notifier.py", line 70, in __init__
    self.team_abbr = NHLTeams.team_dict[team_name]
KeyError: 'Montréal Canadiens'
Exception 'Montréal Canadiens'
Traceback (most recent call last):
  File "notifier.py", line 202, in check_nhl
    game_date)
  File "notifier.py", line 45, in __init__
    self.home = Team(home, home_score)
  File "notifier.py", line 70, in __init__
    self.team_abbr = NHLTeams.team_dict[team_name]
KeyError: 'Montréal Canadiens'
Exception 'Montréal Canadiens'
Traceback (most recent call last):
  File "notifier.py", line 202, in check_nhl
    game_date)
  File "notifier.py", line 45, in __init__
    self.home = Team(home, home_score)
  File "notifier.py", line 70, in __init__
    self.team_abbr = NHLTeams.team_dict[team_name]
KeyError: 'Montréal Canadiens'
Exception 'Montréal Canadiens'
Traceback (most recent call last):
  File "notifier.py", line 202, in check_nhl
    game_date)
  File "notifier.py", line 45, in __init__
    self.home = Team(home, home_score)
  File "notifier.py", line 70, in __init__
    self.team_abbr = NHLTeams.team_dict[team_name]
KeyError: 'Montréal Canadiens'

**Comment by ephro** [comment]
This should be fixed in the last push. Looks like NHL added the accent to the Canadiens from last year.

**Comment by tabooki** [comment]
That worked. I now have my lights blinking blue and white whenever the Leafs score. 
My only issue now is with Hue or maybe it's IFTTT. In my recipe I get the alert from you. This triggers a Hue scene where to change the lighting colours. It then triggers a Hue blink off and on again. 

The problem is that the lights are then left in the blue state. It seems that you can only use each Hue ingredient once in a recipe. Ugh.

Still plugging away at it.

Great work on your part though as this was out of my abilities.
Thanks
